# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 650)
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(960, 390, 50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(890, 440, 50, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(820, 190, 50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(820, 320, 50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_pic = QtWidgets.QLabel(Form)
        self.label_pic.setGeometry(QtCore.QRect(740, 50, 331, 451))
        self.label_pic.setStyleSheet("background-image: url(:/newPrefix/face.jpg);")
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 520, 80, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 520, 80, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 520, 80, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(820, 390, 50, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(960, 320, 50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(740, 30, 90, 16))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(890, 220, 50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 520, 80, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(890, 350, 50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(960, 190, 50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(840, 30, 90, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.camView = QtWidgets.QLabel(Form)
        self.camView.setGeometry(QtCore.QRect(20, 30, 640, 480))
        self.camView.setFrameShape(QtWidgets.QFrame.Box)
        self.camView.setText("")
        self.camView.setObjectName("camView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(390, 520, 261, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_11.setText(_translate("Form", "#BR"))
        self.pushButton_10.setText(_translate("Form", "#BC"))
        self.pushButton_3.setText(_translate("Form", "#TL"))
        self.pushButton_6.setText(_translate("Form", "#ML"))
        self.pushButton_12.setText(_translate("Form", "History"))
        self.pushButton_2.setText(_translate("Form", "Report"))
        self.pushButton.setText(_translate("Form", "AutoStart"))
        self.pushButton_9.setText(_translate("Form", "#BL"))
        self.pushButton_8.setText(_translate("Form", "#MR"))
        self.radioButton.setText(_translate("Form", "수동촬영"))
        self.pushButton_4.setText(_translate("Form", "#TC"))
        self.pushButton_13.setText(_translate("Form", "CAM ON"))
        self.pushButton_7.setText(_translate("Form", "#MC"))
        self.pushButton_5.setText(_translate("Form", "#TR"))
        self.radioButton_2.setText(_translate("Form", "분석모드"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; font-weight:600;\">640 x 480 (VGA 4:3)</span></p><p align=\"right\">5M 1080P (1/4&quot;, OV5647) / 36mm / FOV: 70</p><p align=\"right\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
